name: GlobalQuestPunisher
version: 1.0.0
main: dev.mrduck.GlobalQuestPunisher
api-version: 1.20
author: MrDuck
description: A plugin that forces all players to complete global quests or face punishment

commands:
  quest:
    description: Main quest command
    aliases: [globalquest, gq]
    usage: /quest [subcommand]
  globalquest:
    description: Global quest command
    aliases: [quest, gq]
    usage: /globalquest [subcommand]

permissions:
  globalquest.admin:
    description: Allows access to admin quest commands
    default: op
  globalquest.use:
    description: Allows use of basic quest commands
    default: true
